### ISSUE TITLE
Could we use any-db instead of mssql ?

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Fable.SqlClient#1]
any-db is:
> Thin and less-opinionated database abstraction layer for node. 

And it allow you to target any server by providing the correct adapter.

**Comment by Zaid-Ajaj** [comment]
I looked into it and it seems interesting, although I would create a different binding library for it and keep this one specialized and focused on mssql with good tests and docs. I want to make this one production-grade and as you can see, this one is a tiny bit opinionated to look like the `SqlClient` from dotnet.

also any-db doesn't seem to [support promises](https://github.com/grncdr/node-any-db/issues/66) which is a bit of a turn off for me

**Comment by MangelMaxime** [comment]
Ah yes, I forget about the lack of promise support because we created our own layer on top of it ^^
